### ISSUE TITLE
Unsynchronized color

### ISSUE THREAD

**Issue by Jerome226** [TheIcyOne/FancyLamps#3]
color out of sync on the Rainbow Obelisk.
![2020-01-22_20 25 42](https://user-images.githubusercontent.com/55724525/72949184-891b3e80-3d55-11ea-95ea-f3c644cc9b72.png)

**Comment by TheIcyOne** [comment]
Sorry for the delay, does this persist when relogging or reloading the chunk?

**Comment by Jerome226** [comment]
No, the problem happened every time I placed the obelisk. Strangely enough, it seems to be fixed and it won't happen again. I'm closing the issue, thanks ;)
